name: Build DLL

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup DirectX SDK
        run: |
          choco install directx-sdk -y

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild oah.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: oah-dll
          path: |
            **/Release/*.dll
            **/x64/Release/*.dll
